### PR TITLE
Add step for creating the database

### PR DESCRIPTION
**Pull request by chivalry**
Just a missed step in the instructions.

### CODE REVIEW

**Comment by chivalry** [comment]
I was having trouble running your tests, but adding the `tests/__init__.py` file fixed that.

**Comment by carc1n0gen** [comment]
Hey thanks for noticing that missing step of creating the database. 

For the tests, you don't need the `__init__.py` file.  Running with this command should work:

`PYTHONPATH=. pipenv run pytest`

I guess that should also be in the readme.  Would you be able to verify that works for you and update the PR?

**Comment by carc1n0gen** [comment]
Another section with a heading like "Running Tests" or something

**Comment by chivalry** [comment]
Your correction to how I ran the tests is confirmed to work and I updated the instructions with another step. Didn't seem to warrantees a whole section.

**Pull request merged**
